services:
  db:
    image: mysql:8.0
    container_name: '${PROJECT_NAME}_mysql'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
      - mailhog
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}_wordpress'
    volumes:
      - ./wp_data:/var/www/html
      #- ./setting/php.ini:/var/www/html/php.ini
      #- ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    ports:
      - ${IP}:${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TITLE: ${WP_TITLE}
      WORDPRESS_ADMIN_USER: ${WP_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('VITE_DEV_SERVER', 'true');
        define('SCRIPT_DEBUG', true);
        define('SMTP_HOST', 'mailhog');
        define('SMTP_PORT', 1025);
        define('SMTP_SECURE', '');
        define('SMTP_AUTH', false);
        define('SMTP_DEBUG', true);

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    container_name: '${PROJECT_NAME}_wpcli'
    volumes:
      - ./wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    command: >
      /bin/sh -c '
      wp core install --url=http://127.0.0.1:${WP_PORT} --title="${WP_TITLE}" --admin_user=${WP_ADMIN_USER} --admin_password=${WP_ADMIN_PASSWORD} --admin_email=${WP_ADMIN_EMAIL} --skip-email;
      wp theme activate twentytwentyfour;
      tail -f /dev/null
      '

  mailhog:
    image: mailhog/mailhog
    container_name: '${PROJECT_NAME}_mailhog'
    ports:
      - '${IP}:1025:1025' # SMTPポート
      - '${IP}:8025:8025' # Web UI用ポート
  #phpmyadmin:
  #  image: phpmyadmin
  #  platform: linux/arm64
  #  container_name: '${PROJECT_NAME}_phpmyadmin'
  #  restart: always
  #  depends_on:
  #    - db
  #  ports:
  #    - ${IP}:${PMA_PORT}:80
  #  volumes:
  #    - $PWD/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

volumes:
  db_data:
  wp_data:
